# POST http://localhost:3000/auth/login
# Content-Type: application/json

# {
#   "identifier": "Nuthan",
#   "password": "Nuthan@95"
# }

# ###
# GET http://localhost:3000/members/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJOdXRoYW4iLCJlbWFpbCI6Im51dGhhbi5zQGNvbXZpdmEuY29tIiwiaWF0IjoxNzE2OTg3MzYxLCJleHAiOjE3MTY5OTgxNjF9.DMQt-XaeNDrPSHjUrpflitCBTFa7v_PMOJxVEvRTPIA
# ###
# GET http://localhost:3000/transactions/history/A123
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJOdXRoYW4iLCJlbWFpbCI6Im51dGhhbi5zQGNvbXZpdmEuY29tIiwiaWF0IjoxNzE2NTU2NjM4LCJleHAiOjE3MTY1Njc0Mzh9.mEvuh8jt_tqX4zWuwHN6DD_OqyxcyETroyGHzcYHCMI

# ###
# DELETE http://localhost:3000/members/A124
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ1andhbCIsImVtYWlsIjoidWp3YWwubEBjb212aXZhLmNvbSIsImlhdCI6MTcxNjU1OTg2NywiZXhwIjoxNzE2NTcwNjY3fQ.XwT5EHFjfb6rwoHimG56x9dHQIXe1YCDCrdUuDjcMLo

 GET http://localhost:3000/hello


###
POST http://localhost:5000/api/categories
Content-Type: application/json

{
    "name": "Work",
    "color": "#FF5733"
}

